### ISSUE TITLE
大神  如何添加日线图

### ISSUE THREAD

**Issue by leielyq** [tifezh/KChartView#17]
现在数据都接入进去了，如何添加五分钟，十分钟，一个小时，一天这样的k线图啊

**Comment by leielyq** [comment]
大神回答一下这个问题啊

**Comment by tifezh** [comment]
5分图就是数据间隔时间是5分钟，日k图时间间隔是10分钟，以此类推
这完全取决于你添加的数据，那么只需要设置时间格式化器就行了，比如日k是时间是 年月日（如2017/8/31） ，5分就是 时分(如12:00)
`
//年月日
mKChartView.setDateTimeFormatter(new DateFormatter());
//时分
mKChartView.setDateTimeFormatter(new TimeFormatter());
`
也可以自定义格式化方式

**Comment by leielyq** [comment]
哦哦  原来是按照数据源来的啊  刚接触这个不是很明白  辛苦啦 大神
