### ISSUE TITLE
大神  如何添加新的数据

### ISSUE THREAD

**Issue by leielyq** [tifezh/KChartView#18]
k线图可以加载完成，现在需要根据新数据进行蜡烛图的动态添加，但是没有看到相关的内容，希望大神能回复一下哈

**Comment by tifezh** [comment]
demo里面有例子的啊

**Comment by leielyq** [comment]
不是加载更多 这个形式的   是要添加最新的数据，比如说k线图加载了10.17分的数据，一分钟之后再加载10.18的数据

**Comment by tifezh** [comment]
跟ListView的适配器一样，加了数据，刷新适配器就行了呗
在demo的适配器中有追加集合的方法
`/**
     * 向头部添加数据
     */
    public void addHeaderData(List<KLineEntity> data) {
        if (data != null && !data.isEmpty()) {
            datas.addAll(data);
            notifyDataSetChanged();
        }
    }`
如果你要添加单个实体，自己再加个方法

**Comment by leielyq** [comment]
哦哦  那我明白了  谢谢啦

**Comment by leielyq** [comment]
大神  如何做五分钟  十分钟 一周的k线图啊，是需要修改数据还是改时间格式啊

2017年8月31日 10:57，"tifezh" <notifications@github.com>写道：
