### ISSUE TITLE
大神代码逻辑结构真好

### ISSUE THREAD

**Issue by billsinla** [tifezh/KChartView#2]
赞赞赞

**Comment by tifezh** [comment]
谢谢关注

**Comment by billsinla** [comment]
二分法没有判断就只有一个数据的情况，会出现死循环

**Comment by tifezh** [comment]
是的，已经解决了

**Comment by billsinla** [comment]
如果数据小于一屏的话，缩放不会改变时间轴的时间

**Comment by billsinla** [comment]
大神请问一下，Scale，缩放可以向左边缩小吗
现在是向右边缩小，就是缩小到小于一个屏幕的时候，空白的区域在左边

**Comment by tifezh** [comment]
设计的时候，这个view是从右向左滑动的（刚开始进入的时候查看最新的数据），所以右边是顶部，左边是底部，所以缩放的时候是以右边为基准的，空白就留在了左边部分
