### ISSUE TITLE
怎么在canvas缩放中的指标的文字的宽度不变?

### ISSUE THREAD

**Issue by yangliuchun314** [tifezh/KChartView#4]
1.思路很完美,就是有个缺点是在指标中有画文字的情况下,文字的宽度随着canvas的缩放,宽度改变了,怎么是文字和K线的引线的宽度不变,这个问题,显而易见在指标中有很多这种情况,我们需要画字和别的东西,macd指标的竖线不是柱子而是线,作者估计因为这个问题把线改成了柱子
2.怎么解决指标叠加的时候最大值最小值共享的问题,K线和5.10.20日均线画在一起这个不太好吧.主图里和K线配合的指标有很多,总不能都写在一起吧.
请大神解决,你的缩放的思路是最牛逼的还没见过谁用过.

**Comment by tifezh** [comment]
首先谢谢你的建议及肯定
对于问题1：是想要文字在线上面的那种一起滑动的效果吗，如果是的话现在还没有把相关的方法暴露出来，现在暂时是文字固定的。
对于问题2：主图可以改成多个主图切换（现在暂时是一个主图），就可以达到分离的效果，最大最小值都有相关方法获取的

**Comment by yangliuchun314** [comment]
1.我昨天已经解决了,自己有点傻,我的意思的比如K线上有一个多空提示的字,是随着K线的index滑动的,在canvas缩放的过程中,字也被放大了,所以看起来字扁了.这个倒是不难解决.
2.指标叠加的时候的这个也是经常用到的,倒是不难这个
3.在放大的时候K线会抖动,这个没办法解决,当把屏幕高度缩小时候看不出来,到时屏幕高度大的时候,就很明显了.不过以现在一般的软件的高度的情况下不明显,可以接受.
大神这个思路很牛逼,我把你的代码研究了一周.给缩放提供了新的思路,并且计算量大大缩小了.

**Comment by tifezh** [comment]
会抖动这个问题的确有，我抽空的时候看下
一起学习进步，有什么好的思路也可以提出来哈哈

**Comment by yangliuchun314** [comment]
我的思路哪能和你比,都是模仿你.

**Comment by yangliuchun314** [comment]
还有一个问题,在K线不足个屏幕房置,比如说之后十条的话这个是不是会有问题?
我按照你的思路又重新做了一个demo,就是在整个所有的K线上设定一个区域,平移的时候改变左右的下标,在缩放的时候,也是改变下标,然后截取出来一段数据,然后在计算这一段在屏幕显示的的显示,这样的话计算量减少了很多,也不用canvas的缩放,就只关注当前的屏幕上的K线和相关指标的即可,现在还是半成品,等做出来相互交流交流.希望可以加好友联系QQ:253415675

**Comment by zcm-hu** [comment]
canvas 画的文字 缩放的时候被左右拉伸  楼主是怎么解决的
