### ISSUE TITLE
MA20绘制有点问题

### ISSUE THREAD

**Issue by ciscolxh** [tifezh/KChartView#43]
ma20的起点应该是从第二十个蜡烛图开始绘制，但是demo中的ma20是从 第一个蜡烛图绘制的

**Comment by tifezh** [comment]
不足20个点，取的是n个点的平均值。比如第15个点，n=15

**Comment by ciscolxh** [comment]
再问一个问题，不足一屏幕显示默认是居右显示，如何让默认居左显示呢

**Comment by tifezh** [comment]
很抱歉一直都没有时间去提交修复这个问题 可以看看 #28  最后面有修改方法

**Comment by ciscolxh** [comment]
好的谢谢
