### ISSUE TITLE
关于加载数据显示的问题

### ISSUE THREAD

**Issue by shurrikann** [tifezh/KChartView#5]
如果没有可以填满整个x轴的数据，则数据会从view的右侧，而非左侧开始计算，这个该如何解决？

**Comment by tifezh** [comment]
因为滑动的起始点在右边，所以数据是从右往左开始排列的，所以当数据没有填充满的时候，也是从右往左排列的。

**Comment by shurrikann** [comment]
大神，那这块我要改的话可以改么？可以改的话改怎么改呢？

**Comment by tifezh** [comment]
修改BaseKChartView中的：
`  private float getMinTranslateX() {
        if(!isFullScreen())
        {
            return getMaxTranslateX();
        }
        return -mDataLen + mWidth / mScaleX - mPointWidth / 2;
    }

    private float getMaxTranslateX() {
        return mPointWidth / 2;
    }

    @Override
    public int getMinScrollX() {
        if(!isFullScreen())
        {
            return 0;
        }
        return (int) -(mOverScrollRange / mScaleX);
    }`
看看是不是你想要的效果呢

**Comment by shurrikann** [comment]
好的 我试试 非常感谢

**Comment by shurrikann** [comment]
另外还有一个小问题，关于切屏这个功能是在什么位置？

**Comment by tifezh** [comment]
KChartTabView 里面的点击事件，是通过屏幕旋转来做的。

**Comment by shurrikann** [comment]
遇到数据越界的问题，k线图超出了边界。。

**Comment by shurrikann** [comment]
我把我的数据加到demo里面也是越界，这块是在哪处理的？我想看看

**Comment by tifezh** [comment]
用原始数据也会越界吗？

**Comment by shurrikann** [comment]
原始数据不会。

**Comment by shurrikann** [comment]
应该是数据问题，构造数据的时候有个数据不符合客观规律，开盘价高于最高价，所以画出去了
