### ISSUE TITLE
如何像火币样的最右边留出一些空白?

### ISSUE THREAD

**Issue by wufannet** [tifezh/KChartView#63]
![image](https://user-images.githubusercontent.com/13639215/63823911-f2a24700-c987-11e9-9b50-354c46008053.png)

**Comment by wufannet** [comment]
https://github.com/fujianlian/KLineChart/issues/28 解决了

**Comment by ErenSnow** [comment]
请问可以加您微信进行一下学习交流吗？微信：13073638055，或者留下您的微信我加您，谢谢啦
