### ISSUE TITLE
这个能画分时线吗？

### ISSUE THREAD

**Issue by zhoux122333** [tifezh/KChartView#8]
K线部分真的做的不错

**Comment by tifezh** [comment]
分时图暂时还没有哦，但是分时图相比k线图要简单

**Comment by zhoux122333** [comment]
x轴怎么才能显示分钟的数据呢？做一分钟K线和5分钟K线的那种

**Comment by tifezh** [comment]
setDateTimeFormatter 可以格式化时间的

**Comment by zhoux122333** [comment]
谢谢你的提醒，我开始没有注意这个方法，都用的DateFormatter()，分钟显示用TimeFormatter()的才对

**Comment by silladus** [comment]
分时我已画好并用于项目中，可以去看看我的

**Comment by silladus** [comment]
发现楼主也写了分时。。。
